# Nodes with values to reuse in the pipeline.
common_params:
  - &common_env
    IMAGE_ID: xcode-13.4.1

steps:
  - label: Build and test
    # Notice we _need_ to use a script because of how our CI & VMs management
    # layer currently manages environment variables (which is how we make the
    # Test Analytics token available to the uploader)
    command: .buildkite/commands/build-and-test.sh
    env: *common_env
    agents:
      queue: "default"
